server:
  port: 8080

spring:
  application:
    name: order-service
  jackson:
    default-property-inclusion: non_null
  codec:
    max-in-memory-size: 1048576
    max-request-size: 4400390
    
kafka:
  producer:
    order:
      topic: ${KAFKA_PRODUCER_ORDER_TOPIC:orders}
      bootstrapServers: ${KAFKA_PRODUCER_ORDER_BOOTSTRAP_SERVERS:kafka:9092}
      security:
        username: ${KAFKA_PRODUCER_ORDER_SECURITY_USERNAME:}
        password: ${KAFKA_PRODUCER_ORDER_SECURITY_PASSWORD:}
        trust-store:
          path: ${KAFKA_PRODUCER_ORDER_SECURITY_TRUST_STORE_PATH:}
          password: ${KAFKA_PRODUCER_ORDER_SECURITY_TRUST_STORE_PASSWORD:}

logging:
  level:
    com.epam: ${LOGGING_LEVEL_COM_EPAM:DEBUG}
